global:
  scrape_interval: 5s

scrape_configs:
# 1. ゲーム内情報 (Existing)
  - job_name: 'minecraft-bedrock'
    static_configs:
      - targets: ['192.168.0.20:30001']
        labels:
          group: 'game-stats'

  # 2. システム負荷情報 (cAdvisor)
  - job_name: 'k3s-cadvisor'
    static_configs:
      - targets: ['192.168.0.20:30002']
        labels:
          group: 'system-stats'

 # 3. ログ監視エクスポーター (Log Watcher)
  # K3sのNodePort 30003に向けてスクレイピングを行います
  - job_name: 'minecraft-log-watcher'
    static_configs:
      - targets: ['192.168.0.20:30003']
        labels:
          group: 'log-stats'