---
all:
  children:
    # ----------------------------
    # VM1: DevOps (Dashboard & CI/CD)
    # ----------------------------
    devops_vm:
      hosts:
        192.168.0.21:
          ansible_user: tagomori
          
    # ----------------------------
    # VM2: Minecraft Server (K3s)
    # ----------------------------
    mcbe_server_vm:
      hosts:
        192.168.0.20:
          ansible_user: tagomori
