---
all:
  children:
    # ----------------------------
    # VM1: DevOps (Dashboard & CI/CD)
    # ----------------------------
    devops_vm:
      hosts:
        192.168.0.21:
          ansible_user: tagomori
          
    # ----------------------------
    # VM2: Minecraft Server (K3s)
    # ----------------------------
    mcbe_server_vm:
      hosts:
        192.168.0.22:
          ansible_user: tagomori

# 【追加】新しい開発機
    dev_workstation:
      hosts:
        192.168.0.22:
          ansible_user: tagomori